"""Tests for the YouTube auto-commenter service."""

import pytest

from app.services.yt_commenter import YouTubeCommenterService, _slugify


class TestExtractVideoId:
    """Test video ID extraction from various URL formats."""

    def setup_method(self):
        self.service = YouTubeCommenterService.__new__(YouTubeCommenterService)

    def test_standard_url(self):
        url = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
        assert self.service._extract_video_id(url) == "dQw4w9WgXcQ"

    def test_short_url(self):
        url = "https://youtu.be/dQw4w9WgXcQ"
        assert self.service._extract_video_id(url) == "dQw4w9WgXcQ"

    def test_shorts_url(self):
        url = "https://www.youtube.com/shorts/dQw4w9WgXcQ"
        assert self.service._extract_video_id(url) == "dQw4w9WgXcQ"

    def test_embed_url(self):
        url = "https://www.youtube.com/embed/dQw4w9WgXcQ"
        assert self.service._extract_video_id(url) == "dQw4w9WgXcQ"

    def test_url_with_extra_params(self):
        url = "https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=120&list=PLabc"
        assert self.service._extract_video_id(url) == "dQw4w9WgXcQ"

    def test_mobile_url(self):
        url = "https://m.youtube.com/watch?v=dQw4w9WgXcQ"
        assert self.service._extract_video_id(url) == "dQw4w9WgXcQ"

    def test_plain_video_id(self):
        assert self.service._extract_video_id("dQw4w9WgXcQ") == "dQw4w9WgXcQ"

    def test_invalid_url(self):
        assert self.service._extract_video_id("https://example.com") is None

    def test_empty_string(self):
        assert self.service._extract_video_id("") is None

    def test_none(self):
        assert self.service._extract_video_id(None) is None

    def test_url_with_hyphen_underscore_id(self):
        url = "https://www.youtube.com/watch?v=Ab_C-d1E2F3"
        assert self.service._extract_video_id(url) == "Ab_C-d1E2F3"


class TestFormatComment:
    """Test comment formatting."""

    def setup_method(self):
        self.service = YouTubeCommenterService.__new__(YouTubeCommenterService)

    def test_full_comment(self):
        comment = self.service._format_comment(
            title="Test Talk",
            summary="This is a test summary of the talk.",
            loc="conferences/test-conf",
        )
        assert "📝 AI-Generated Transcript Summary" in comment
        assert "📌 Test Talk" in comment
        assert "This is a test summary of the talk." in comment
        assert "🔗 Full transcript:" in comment
        assert "conferences/test-conf/test-talk" in comment
        assert "🤖 Generated by BitScribe" in comment

    def test_comment_without_title(self):
        comment = self.service._format_comment(
            title="",
            summary="Summary without title.",
        )
        assert "📌" not in comment
        assert "Summary without title." in comment

    def test_comment_without_loc(self):
        comment = self.service._format_comment(
            title="Some Title",
            summary="Summary text.",
            loc="",
        )
        assert "🔗 Full transcript:" not in comment
        assert "Summary text." in comment


class TestSlugify:
    """Test the slugify helper."""

    def test_basic(self):
        assert _slugify("Hello World") == "hello-world"

    def test_special_chars(self):
        assert _slugify("Bitcoin: A P2P Cash System!") == "bitcoin-a-p2p-cash-system"

    def test_extra_spaces(self):
        assert _slugify("  lots   of   spaces  ") == "lots-of-spaces"

    def test_unicode(self):
        result = _slugify("Café & Bitcoin")
        assert "caf" in result
